crowdfunding/auth_app/urls.py
from django.contrib import admin
from django.urls import path
from django.db import models
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
                  path('register', views.register, name='register'),
                  path('', views.login, name='login'),
                  path('verify/<int:user_id>/', views.verify_email, name='verify_email'),
                  path('profile', views.profile, name='profile'),
                  path('editProfile', views.editProfile, name='edit_profile'),
                  path('deleteAccount', views.deleteAccount, name='deleteAccount'),
                  path('delete/<int:user_id>', views.confirmDeleteAccount, name='delete_account'),
                  path('logout', views.logout, name='logout'),
                  path('resetpassword', views.resetPassword, name='resetpassword'),
                  path('setpassword/<str:email>', views.sendEmailPassword, name='setpassword'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfunding/crowdfunding/urls.py
from django.contrib import admin
from django.urls import path,include
from projects_app import  urls as projcets_urls
from django.shortcuts import render
from django.contrib import admin
from django.urls import path, include  # add this
from django.conf.urls.static import static
from django.conf import settings
from home_page_app import urls as home_page
from auth_app import urls as auth_url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include(projcets_urls)),
    path('homePage/',include(home_page)),
    path('',include(auth_url)),
path('verification/', include('verify_email.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowdfunding/projects_app/forms.py
from datetime import datetime

from django import forms
from .models import *
from django.forms.widgets import NumberInput


class ProjectForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Type tile",
                "class": "form-control"
            }
        ))

    details = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "placeholder": "Type details",
                "class": "form-control",
                'rows': '2'
            }
        ))

    total_target = forms.FloatField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Type Total Target",
                "class": "form-control",
                           }
        ))

    start_time = forms.DateTimeField(
        widget=NumberInput(
            attrs={
                'placeholder': 'Start date',
                'type': 'datetime-local',
                'class': 'form-control'
            }
        ))

    end_time = forms.DateTimeField(
        widget=NumberInput(
            attrs={
                'placeholder': 'End date',
                'type': 'datetime-local',
                'class': 'form-control'
            }
        ))

    category = forms.ModelChoiceField(queryset=Category.objects.all(),
                                      widget=forms.Select(
                                          attrs={
                                              "class": "form-control"
                                          }
                                      ))

    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                         widget=forms.CheckboxSelectMultiple())

    def clean(self):
        data = super().clean()
        start_date = data.get("start_time")
        end_date = data.get("end_time")
        today_date = datetime.strptime(datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "%Y-%m-%d %H:%M:%S")
        if today_date.date() > end_date.date():
            self._errors["end_time"] = self.error_class(["End date should be greater than Current date"])
        else:
            if end_date <= start_date:
                self._errors["end_time"] = self.error_class(["End date should be greater than start date."])
        total_target=data.get("total_target")
        if total_target<100:
            self._errors["total_target"] = self.error_class(["total target should great than 100 "])

    class Meta:
        model = Project
        fields = ('title',
                  'details',
                  'total_target',
                  'start_time',
                  'end_time',
                  'category',
                  'tag')


class ReplyForm(forms.ModelForm):

    class Meta:
        model=Reply
        fields =['reply']

crowdfunding/templates/projects/add_project.html
{% extends 'base_page.html' %}
{% block title %} Create Project {% endblock title %}
 {% block mystyle %}

 {% endblock mystyle %}
{% block content %}
{{ categories }}
<form role="form"  method="post" autocomplete="off" enctype="multipart/form-data">
 {%csrf_token%}
 <div id="svg_wrap"></div>
<h1 style="text-align:center">Add  Project</h1>
<section>
 <p>Project information</p>
  <div class="mb-3">
            <label class="form-label">Project Title</label>
            {{ form.title }}
          </div>
          <span class="text-error">{{ form.title.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Details</label>
            {{ form.details }}
          </div>
          <span class="text-error">{{ form.details.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Total Target</label>
            {{ form.total_target }}
          </div>
          <span class="text-error">{{ form.total_target.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Start Date & Time</label>
            {{ form.start_time }}
          </div>
          <span class="text-error">{{ form.start_time.errors }}</span>

          <div class="mb-3">
            <label class="form-label">End Date & Time</label>

            {{ form.end_time }}
          </div>
          <span class="text-error">{{ form.end_time.errors }}</span>
</section>


<section>
 <p>project information tag and categories</p>
<div class="mb-3">
            <label class="form-label">Category</label>

            {{ form.category }}
          </div>
          <span class="text-error">{{ form.category.errors }}</span>


          <div class="mb-3">
            <label class="form-label">Add tag</label>
            <input type="text" class="inp form-control my-1" maxlength="8" name="newTag" class="form-control"  id="id_tag"/>
            <p style="margin: 2px; color: black; font-size: small; font-weight: 550;">or choose one : </p>

                     {{ form.tag }}
          </div>
          <span class="text-error">{{ form.tag.errors }}</span>

</section>


    <section>
 <p>images</p>
     <div class="mb-3">
            <label class="form-label">Photos</label><br />
            <input class="form-control" type="file" name="images" multiple required>
          </div>
</section>
<section>
 <p>General condtitions</p>
 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</section>
<div class="container" style="text-align:center">
 <div class="button" id="prev">&larr; Previous</div>
<div class="button" id="next">Next &rarr;</div>
<input class="button" id="submit" type="submit" style="width:25%" value="Agree and send application">

</div>
 </form>
{% endblock content %}